# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-27 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_auto_20180427_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='wished_by',
            field=models.ManyToManyField(related_name='wished_by', to='Login.User'),
        ),
        migrations.AlterField(
            model_name='item',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
